name: auth_module
description: Authentication microapp module.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  core_network:
    path: ../core_network
  module_contracts:
    path: ../module_contracts
  shared_ui:
    path: ../shared_ui
